version: '3.7'
services:
  ntsim-ng:
    image: "${DOCKER_REPO}nts-ng-base:latest"
    command: ["/opt/dev/ntsim-ng/ntsim-ng", "-w/opt/dev/ntsim-ng", "--supervisor"]
    container_name: nts-ng-debug
    stop_grace_period: 5m
    volumes:
     - "./yang:/opt/dev/deploy/yang"
     - "./data:/opt/dev/deploy/data"
     - "./config.json:/opt/dev/ntsim-ng/config/config.json"
    environment:
      IPv6_ENABLED: ${IPv6_ENABLED}
      SSH_CONNECTIONS: ${SSH_CONNECTIONS}
      TLS_CONNECTIONS: ${TLS_CONNECTIONS}
      NTS_NF_STANDALONE_START_FEATURES: ${NTS_NF_STANDALONE_START_FEATURES}
      NTS_NF_MOUNT_POINT_ADDRESSING_METHOD: ${NTS_NF_MOUNT_POINT_ADDRESSING_METHOD}

      NTS_HOST_IP: ${NTS_HOST_IP}
      NTS_HOST_BASE_PORT: ${NTS_HOST_BASE_PORT}
      NTS_HOST_NETCONF_SSH_BASE_PORT: ${NTS_HOST_NETCONF_SSH_BASE_PORT}
      NTS_HOST_NETCONF_TLS_BASE_PORT: ${NTS_HOST_NETCONF_TLS_BASE_PORT}
      NTS_HOST_TRANSFER_FTP_BASE_PORT: ${NTS_HOST_TRANSFER_FTP_BASE_PORT}
      NTS_HOST_TRANSFER_SFTP_BASE_PORT: ${NTS_HOST_TRANSFER_SFTP_BASE_PORT}

      SDN_CONTROLLER_PROTOCOL: ${SDN_CONTROLLER_PROTOCOL}
      SDN_CONTROLLER_IP: ${SDN_CONTROLLER_IP}
      SDN_CONTROLLER_PORT: ${SDN_CONTROLLER_PORT}
      SDN_CONTROLLER_CALLHOME_IP: ${SDN_CONTROLLER_CALLHOME_IP}
      SDN_CONTROLLER_CALLHOME_PORT: ${SDN_CONTROLLER_CALLHOME_PORT}
      SDN_CONTROLLER_USERNAME: ${SDN_CONTROLLER_USERNAME}
      SDN_CONTROLLER_PASSWORD: ${SDN_CONTROLLER_PASSWORD}

      VES_COMMON_HEADER_VERSION: ${VES_COMMON_HEADER_VERSION}
      VES_ENDPOINT_PROTOCOL: ${VES_ENDPOINT_PROTOCOL}
      VES_ENDPOINT_IP: ${VES_ENDPOINT_IP}
      VES_ENDPOINT_PORT: ${VES_ENDPOINT_PORT}
      VES_ENDPOINT_AUTH_METHOD: ${VES_ENDPOINT_AUTH_METHOD}
      VES_ENDPOINT_USERNAME: ${VES_ENDPOINT_USERNAME}
      VES_ENDPOINT_PASSWORD: ${VES_ENDPOINT_PASSWORD}

      CURL_CONNECT_TIMEOUT: ${CURL_CONNECT_TIMEOUT}
      CURL_OPERATION_TIMEOUT: ${CURL_OPERATION_TIMEOUT}
