var configs = {
        "elsbaseurl": "https://192.168.128.77:9200",
        "apibaseurl": "http://192.168.128.77:3001",
        "REACT_APP_EMS_TIME_ZONE": "PLACEHOLDER_REACT_APP_EMS_TIME_ZONE",
        "NBI_ALLOWED_ARRAY_LIMIT": "PLACEHOLDER_NBI_ALLOWED_ARRAY_LIMIT",
        "SOFTWARE_NOTIFICATION_WAIT_LIMIT": "PLACEHOLDER_SOFTWARE_NOTIFICATION_WAIT_LIMIT",

};
