################################################################################
# Copyright (C) 2024 RideNext Software Solutions. Pvt Ltd
# Copyright 2021 highstreet technologies GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.8'

x-common_env: &common_env
    IPv6_ENABLED: ${IPv6_ENABLED}
    SSH_CONNECTIONS: ${SSH_CONNECTIONS}
    TLS_CONNECTIONS: ${TLS_CONNECTIONS}
    NTS_NF_MOUNT_POINT_ADDRESSING_METHOD: ${NTS_NF_MOUNT_POINT_ADDRESSING_METHOD}

    NTS_HOST_IP: ${NTS_HOST_IP}
    NTS_HOST_BASE_PORT: ${NTS_HOST_BASE_PORT}
    NTS_HOST_NETCONF_SSH_BASE_PORT: ${NTS_HOST_NETCONF_SSH_BASE_PORT}
    NTS_HOST_NETCONF_TLS_BASE_PORT: ${NTS_HOST_NETCONF_TLS_BASE_PORT}
    NTS_HOST_TRANSFER_FTP_BASE_PORT: ${NTS_HOST_TRANSFER_FTP_BASE_PORT}
    NTS_HOST_TRANSFER_SFTP_BASE_PORT: ${NTS_HOST_TRANSFER_SFTP_BASE_PORT}

    SDN_CONTROLLER_PROTOCOL: ${SDN_CONTROLLER_PROTOCOL}
    SDN_CONTROLLER_IP: ${SDNC_OAM_IPv6}
    SDN_CONTROLLER_PORT: ${SDNC_REST_PORT}
    SDN_CONTROLLER_CALLHOME_IP: ${SDNC_OAM_IPv6}
    SDN_CONTROLLER_CALLHOME_PORT: ${SDN_CONTROLLER_CALLHOME_PORT}
    SDN_CONTROLLER_USERNAME: ${ADMIN_USERNAME}
    SDN_CONTROLLER_PASSWORD: ${ADMIN_PASSWORD}

    VES_COMMON_HEADER_VERSION: ${VES_COMMON_HEADER_VERSION}
    VES_ENDPOINT_PROTOCOL: ${VES_ENDPOINT_PROTOCOL}
    VES_ENDPOINT_IP: ${VES_COLLECTOR_OAM_IPv6}
    VES_ENDPOINT_PORT: ${VES_ENDPOINT_PORT}
    VES_ENDPOINT_AUTH_METHOD: ${VES_ENDPOINT_AUTH_METHOD}
    VES_ENDPOINT_USERNAME: ${VES_ENDPOINT_USERNAME}
    VES_ENDPOINT_PASSWORD: ${VES_ENDPOINT_PASSWORD}

    ##
    ## FEATURE: "YES" Value means feature enabled 
    #           "NO" means ; feay=ture diabled
    #  EVENT:  "POS" means, send success event
    #          "NEG" send the falilure event
    ##
x-du_env: &du_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate ves-heartbeat ves-file-ready ves-pnf-registration ves-o1-pnf-registration web-cut-through sw_mgnt"
    NTS_VES_FILE_NOTIFY_DURATION: 300
    NTS_VES_FILE_NOTIFY_FEATURE: "YES"
    NTS_VES_FILE_DIR: "/opt/dev/deploy/data/pmxml"
    NTS_VES_FTP_FILE_PATH: "sftp://rnacumos:test123@192.168.128.77:22/home/rnacumos/Manish/rn-ems/exec/networkElement/ntsim-ng-o-du/pmxml/"
    NTS_SW_MGNT_FEATURE: "YES"
    NTS_SW_DWLOAD_STATUS_EVNT: "POS"
    NTS_SW_INSTALL_STATUS_EVNT: "POS"
    NTS_SW_ACTIVE_STATUS_EVNT: "POS"

x-ru-env: &ru_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate netconf-call-home web-cut-through"

x-topo-env: &topo_env
    NTS_NF_STANDALONE_START_FEATURES: "datastore-populate netconf-call-home web-cut-through"

x-nf: &common_nf
    stop_grace_period: 5m
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE

services:
  ntsim-ng-o-ru-fh-11221:
    <<: *common_nf
    image: "${NEXUS3_DOCKER_REPO}nts-ng-o-ran-ru-fh:${NTS_BUILD_VERSION}"
    #image: oru:1.0
    #image: du-simulator:sslsim20
    container_name: ntsim-ng-o-ru-fh-11221
    hostname: O-RU-11221
    volumes:
        - ./ntsim-ng-o-ru/ntsim-ng-o-ru-fh-1/config.json:/opt/dev/ntsim-ng/config/config.json
        - ./ntsim-ng-o-ru/ntsim-ng-o-ru-fh-1/ietf-hardware-operational.json:/opt/dev/deploy/data/ietf-hardware-operational.json
        - ./ntsim-ng-o-ru/ntsim-ng-o-ru-fh-1/ietf-hardware-running.json:/opt/dev/deploy/data/ietf-hardware-running.json
        - ./ntsim-ng-o-ru/ntsim-ng-o-ru-fh-1/ietf-interfaces-operational.xml:/opt/dev/deploy/data/ietf-interfaces-operational.xml
        - ./ntsim-ng-o-ru/ntsim-ng-o-ru-fh-1/ietf-interfaces-running.xml:/opt/dev/deploy/data/ietf-interfaces-running.xml
    environment:
        <<: *common_env
        <<: *ru_env

networks:
    default:
        external:
            name: oam
